### ISSUE TITLE
18650 holder has wrong polarity

### ISSUE THREAD

**Issue by crnorris** [KiCad/Battery_Holders.pretty#16]
The 18650 holder footprint has + and - terminals the wrong way around.

Applies to both the silcreen and the pins. See http://www.mouser.com/ds/2/215/042-744829.pdf

**Comment by Shackmeister** [comment]
That it absolutely true! nicely spotted
Im gonna have to call my PCB manufacturer and ask if my board went into production or if I can get this fixed before :/

can you make a PR for the fix or should I do it?

**Comment by Shackmeister** [comment]
moving the extra mounting hole to the other corner should be sufficient as far as I can see?

**Comment by Shackmeister** [comment]
PR has been made

**Comment by evanshultz** [comment]
PR merged.
